const category = [
  {
    id: 1,
    name: 'Pulsa/Data',
    icon: 'cellphone-iphone',
    color: '#347AF0',
    size: 30,
    onPress: () => alert('click'),
  },
  {
    id: 2,
    name: 'Listrik',
    icon: 'electric-switch',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 3,
    name: 'PDAM',
    icon: 'water-pump',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 4,
    name: 'TV Kabel',
    icon: 'youtube-tv',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 5,
    name: 'Internet',
    icon: 'lan-connect',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 6,
    name: 'Telephon',
    icon: 'phone-classic',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 7,
    name: 'GAS',
    icon: 'gas-cylinder',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 8,
    name: 'Properti',
    icon: 'warehouse',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 9,
    name: 'Pendidikan',
    icon: 'school',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 10,
    name: 'Kereta',
    icon: 'train',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 11,
    name: 'Taxi',
    icon: 'taxi',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 12,
    name: 'Bus',
    icon: 'bus',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 13,
    name: 'Pesawat',
    icon: 'airplane',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 14,
    name: 'Kartu Uang Elektronik',
    icon: 'contactless-payment',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 15,
    name: 'Multi Finance',
    icon: 'finance',
    color: '#347AF0',
    size: 30,
  },
  {
    id: 16,
    name: 'Pinjaman',
    icon: 'credit-card-outline',
    color: '#347AF0',
    size: 30,
  },
];
